#pragma once
#include <Windows.h>
#include <memory>
#include <vector>
#include <string>
#include <math.h>
#include <iostream>
#include <algorithm>  
#include <chrono>
#include <fstream>
#include <processthreadsapi.h>
#include <vector>
#include <numeric>
#include <winnt.h>
#include <tchar.h>
#include <strsafe.h>
#include <io.h>
#include <fcntl.h>
#include <iterator>