#pragma once
#include <Windows.h>
#include <memory>
#include <vector>
#include <string>
#include <math.h>
#include <iostream>
#include <algorithm>
#include <chrono>
#include <fstream>
#include <iterator>
#include <regex>